services:
  enerops-db:
    image: timescale/timescaledb:latest-pg15
    container_name: enerops-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  backend:
    image: hemanathan18/enerops-backend:latest
    container_name: enerops-backend
    restart: always
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@enerops-db:5432/${POSTGRES_DB}
    depends_on:
      - enerops-db

  frontend:
    image: hemanathan18/enerops-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: enerops-frontend
    restart: always
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: enerops-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  timescaledb_data:
    driver: local
