services:
  # TimescaleDB Database
  enerops-db:
    image: timescale/timescaledb:latest-pg15
    container_name: enerops-db
    restart: always
    environment:
      POSTGRES_DB: enerops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  # FastAPI Backend
  backend:
    image: hemanathan18/enerops-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: enerops-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgrespassword@enerops-db:5432/enerops
    depends_on:
      - enerops-db

  # Next.js Frontend
  frontend:
    image: hemanathan18/enerops-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: enerops-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  timescaledb_data:
    driver: local
