name: Deploy EnerOps to AWS EC2

on:
  push:
    branches:
      - master # Illana main-a irundha 'main'-nu mathikonga

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_API_URL=http://32.197.41.172
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/enerops-frontend:latest

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/enerops-backend:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create folder and fix permissions
            mkdir -p ~/enerops
            sudo chown -R ubuntu:ubuntu ~/enerops

            # Update .env file
            cat << 'EOF' > ~/enerops/.env
            ${{ secrets.ENV_FILE }}
            EOF

      - name: Copy Compose & Nginx Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,nginx.conf"
          target: "~/enerops/"

      - name: Restart Application Containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/enerops
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans
